### ISSUE TITLE
[Bug]: generate: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by mmahut** [stepci/plugin-openapi#12]
### What happened?

`stepci generate` errors with

```
$ stepci generate ./openapi.yaml ./workflow.yml
stepci generate [spec] [path]

generate workflow from OpenAPI spec

Positionals:
  spec                    openapi file url    [string] [default: "openapi.json"]
  path                    output file path  [string] [default: "./workflow.yml"]
  generatePathParams                                   [boolean] [default: true]
  generateOptionalParams                               [boolean] [default: true]
  generateRequestBody                                  [boolean] [default: true]
  useExampleValues                                     [boolean] [default: true]
  useDefaultValues                                     [boolean] [default: true]
  checkStatus                                          [boolean] [default: true]
  checkExamples                                        [boolean] [default: true]
  checkSchema                                          [boolean] [default: true]
  contentType                             [string] [default: "application/json"]

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

TypeError: Cannot read properties of undefined (reading 'forEach')
    at generateWorkflow (blockfrost-stepci/node_modules/@stepci/plugin-openapi/index.js:186:42)
    at async generateWorkflowFile (node_modules/@stepci/plugin-openapi/index.js:197:45)
    at async Object.handler (node_modules/stepci/dist/index.js:137:5)
```

### What did you expect to happen?

To get a nice workflow :)

### Version

2.6.2

### Environment

v16.16.0

### How can we reproduce this bug?

Take [this open api file](https://github.com/blockfrost/openapi/blob/master/openapi.yaml) and try it.

### Relevant log output

```
TypeError: Cannot read properties of undefined (reading 'forEach')
    at generateWorkflow (/home/mmahut/repo/Blockfrost/blockfrost-stepci/node_modules/@stepci/plugin-openapi/index.js:186:42)
    at async generateWorkflowFile (/home/mmahut/repo/Blockfrost/blockfrost-stepci/node_modules/@stepci/plugin-openapi/index.js:197:45)
    at async Object.handler (/home/mmahut/repo/Blockfrost/blockfrost-stepci/node_modules/stepci/dist/index.js:137:5)
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

**Comment by Century-ss** [comment]
@mishushakov 
The problem is that a tag that exists in each API operation does not exist in global tags section, causing an object key error.
`Nut.link` is an example of this.
[global tags section](https://github.com/blockfrost/openapi/blob/6bc91fb8aa3f96da2204bbde35e4b8feb1830244/openapi.yaml#L255-L273)
[each API operation](https://github.com/blockfrost/openapi/blob/6bc91fb8aa3f96da2204bbde35e4b8feb1830244/openapi.yaml#L5069)

I have created a PR that solves this problem and would be grateful if you could check it.→https://github.com/stepci/plugin-openapi/pull/17
Any suggestion is welcome, of course.
